export const SET_THEME = 'SET_THEME';
export const SET_FONT = 'SET_FONT';
export const SET_ACCENT = 'SET_ACCENT';
export const GET_EXCLUDED_URL = 'GET_EXCLUDED_URL';
export const ADD_EXCLUDED_URL = 'ADD_EXCLUDED_URL';
export const REMOVE_EXCLUDED_URL = 'REMOVE_EXCLUDED_URL';
export const REMOVE_ALL_EXCLUDED_URLS = 'REMOVE_ALL_EXCLUDED_URLS';
export const SET_INCOGNITO = 'SET_INCOGNITO';
