export const GET_HISTORY = 'GET_HISTORY';
export const GET_RECENT_TABS = 'GET_RECENT_TABS';
export const GET_OTHER_TABS = 'GET_OTHER_TABS';
export const SEARCH_HISTORY = 'SEARCH_HISTORY';
export const UPDATE_ACTIVE_TAB_NUM = 'UPDATE_ACTIVE_TAB_NUM';
export const DELETE_HISTORY = 'DELETE_HISTORY';
