name: Extension Continuos Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches:  [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Build and zip the build (dist) folder
        run: yarn run deploy-build

      - name: Get package info
        uses: codex-team/action-nodejs-package-info@v1
        id: package

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package.outputs.name }}-v${{ steps.package.outputs.version }}
          path: ./*.zip
          retention-days: 30
    

