name: Extension Continuos Integration

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches:  [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm run deploy-build