name: Extension Continuos Integration

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches:  [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup yarn
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          yarn
          yarn run deploy-build
      - name: Archive prouction artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: zip dist folder
          path: dist
    

