name: Extension Continuos Integration

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches:  [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: 16
      - run: yarn
      - run: yarn run deploy-build

